### ISSUE TITLE
Неверный Стиль кнопки Сохранить на странице "Профиль организации"

### ISSUE THREAD

**Issue by zuhijan** [cohort52/uvalery#18]
Сейчас отображается:
<img width="527" alt="Screenshot 2022-09-11 at 23 18 43" src="https://user-images.githubusercontent.com/55396077/189547287-49a5a2cf-590e-4479-8cad-aeb490dd48c1.png">

По макету Должно отображаться:
<img width="375" alt="Screenshot 2022-09-11 at 23 19 12" src="https://user-images.githubusercontent.com/55396077/189547298-f13d24a8-2841-4ef5-b7c3-37d88e6e8b36.png">

**Comment by Anastacia-Tesli** [comment]
![Image](https://user-images.githubusercontent.com/107041912/190104584-90b15aec-51b1-4e41-980a-b688e5b89bee.jpg)

Зашла делать задание, а вроде бы корректно отображается )

**Comment by zuhijan** [comment]
@zuhijan хмм странно, действительно! 
И такое бывает - баг уже и не баг со временем )

Бери другое good first issue - одно лишнее точно было 
- а это можно закррыть:)

**Comment by Anastacia-Tesli** [comment]
@zuhijan Запишу закрытие несуществующих проблем в свое резюме ))
