### ISSUE TITLE
 Страница "Важные встречи" и lazy-loading

### ISSUE THREAD

**Issue by zuhijan** [cohort52/uvalery#32]
- необходимо сверстать страницу по макету
- добавить в хедер пункт "Важные встречи" и открывать страницу по клику на него
- подготовить массив данных с ссылками на любые видео
- из массива отрисовать видео на страницу 
- если нужно использовать template
- на странице изначально показывается 8 видео
- при сколле вниз - новые карточки должны подгружаться автоматом (как на главной youtube) - то есть нужно реализовать lazy-loading на js

дополнительное задание:
- для каждого видео должно быть кастомное "превью" - то есть изначально показывается лишь картинка - при клике на нее уже запускается видео
- ссылка на картинку также берется из объекта в массиве

https://www.figma.com/file/nZgu7vsaGd4rdTuvl9YbGO/%F0%9F%A6%9C-uvalery.ru?node-id=3075%3A1538

**Comment by Allxy** [comment]
@zuhijan можно же использовать плеер ютуба или яндекса, а не через <video> вставлять все это дело, я понятия не имею где брать столько ссылок на исходники видео
