### ISSUE TITLE
Нужно 3 человека на роль - "вливателя"

### ISSUE THREAD

**Issue by zuhijan** [cohort52/uvalery#36]
После того, как Пул Реквесты получили апрувы на ревью - существуют разные правила - кто должен нажать кнопку "Merge":
- вливает Автор Пул Реквеста
- вливает последний Ревьюер
- вливает Тимлид или специальный человек

У нас - так как все мы здесь еще "новички в работе с Гит", имеет право вливать только "Тимлид-Наставник)

Но Тимлид занятой, и он недоступен очень часто, поэтому мы добавим еще "3 специальных человека"
Поэтому нужны желающие, готовые взять на себя это почетное звание и разделить ответственность. 

От человека с такой ролью будет требоваться:
- просмотреть ПР, убедиться что все замечания исправлены и нет конлифктов
- нажать кнопку "Merge"

Если вы желаете - пишите об этом в комментарии в этой задаче

**Comment by zuhijan** [comment]
@Allxy @egtalovikov отлично ребята! Даю добро! 
Еще 1 человека можно. 

И если будет чувствоваться, что не хватает людей - пишите

**Comment by Anastacia-Tesli** [comment]
✋🏻младшим вливателем можно попробовать? )

**Comment by zuhijan** [comment]
@Anastacia-Tesli отлично, добро!
