### ISSUE TITLE
Nested БЭМ и EditorConfig

### ISSUE THREAD

**Issue by egtalovikov** [cohort52/uvalery#47]
Предлагаю придать более красивый вид файловой структуре, вынести элементы в блоках в отдельные css-файлы, папку fonts в vendor и добавить .editorconfig для более удобной совместной работы. Что думаете? :)

**Comment by Allxy** [comment]
Хорошая идея

**Comment by CyrilLaz** [comment]
с другой стороны это затронет весь проект, и делать его или сразу в начале или в конце...

**Comment by egtalovikov** [comment]
> с другой стороны это затронет весь проект, и делать его или сразу в начале или в конце...

Да, файловую структуризацию точно в конце делать, иначе всё сломается у тех, кто уже начал, а остальное можно и сейчас)

**Comment by zuhijan** [comment]
@egtalovikov отличная идея!

Давайте разобьем это на ишью - отдельная маленькая задача - отдельное ишью  с четким результатом.
каждый css блок - тоже можно оформить как отдельное ишью - чтобы на одного человека все не сгружалось.

@CyrilLaz хорошо подметил - но, это пугает, только потому что мы еще не умеем работать с конфликтами и вовремя обновляться из основной ветки  - но в целом да, если создать ишью - можно им приоритеты задать - и пометить их "низким" приоритетом

**Comment by zuhijan** [comment]
@AlinaRashitova здесь пригодится помощь,
Нужно разбить задачу "вынести элементы в блоках в отдельные css-файлы" на несколько issues
примерно каждое ищью будет выглядить так:
название: "Рефакторинг БЭМ блока banner" 
описание:  "ссылка на код блока на гитхабе", и комментарий что-то типо "Разнести блок на валидную файлую структуру по БЭМ Nested

и так для каждого блока
