### ISSUE TITLE
Баг в селекторе "Выберите город"

### ISSUE THREAD

**Issue by zuhijan** [cohort52/uvalery#9]
По умолчанию отображается город "Москва", а должен отображаться по умолчанию "Омск"

DoD:
<img width="1002" alt="Screenshot 2022-09-11 at 22 23 16" src="https://user-images.githubusercontent.com/55396077/189545394-ad4901d7-9b35-4b32-aab0-0fbd661746c1.png">

**Comment by CyrilLaz** [comment]
можно посчитать придиркой, но по макету, который я вижу: по умолчанию стоит Москва в placeholder-е 

![Image](https://user-images.githubusercontent.com/19996258/190052202-51b16d08-bb8c-4f2c-8520-9b55e2ec398b.png)
